-- Password hash values below are generated by bcrypt.
-- admin@library.local / admin123
INSERT INTO users (name, email, password_hash, role, created_at, updated_at)
VALUES (
  'Library Admin',
  'admin@library.local',
  '$2b$10$eVTFHd5lhNcgXM0qiH8EnuiEt4xyMepXzF7149D8cDmi2TAUzHTpO',
  'admin',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- user1@example.com / 123456
INSERT INTO users (name, email, password_hash, role, created_at, updated_at)
VALUES (
  'User One',
  'user1@example.com',
  '$2b$10$1qu6Sgc/HQA18on5H/KzRuJtRJjnzXKqfLEA/cKV2x.3FWziHKi/2',
  'user',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT INTO books (title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at)
VALUES
('Clean Code', 'Robert C. Martin', '9780132350884', 2008, 6, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refactoring', 'Martin Fowler', '9780201485677', 1999, 4, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Design Patterns', 'Erich Gamma', '9780201633610', 1994, 5, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('The Pragmatic Programmer', 'Andrew Hunt', '9780201616224', 1999, 7, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Code Complete', 'Steve McConnell', '9780735619678', 2004, 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Domain-Driven Design', 'Eric Evans', '9780321125217', 2003, 2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
